export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import './globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <nav className='bg-slate-800'>
          <ul>
            <li ><p className='text-white text-2xl text-center'>Hello Boss</p></li>
          </ul>
        </nav>
        <main className='h-full'>{children}</main>
        <footer className='bottom-0'>
         <p>@Coppy</p>
        </footer>
        </body>

    </html>
  )
}
